services:
  postgres:
    image: postgres:17-alpine
    container_name: tt4d-postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tt4d-network

networks:
  tt4d-network:
    driver: bridge

volumes:
  postgres_data:
