"""init db schema

Revision ID: 83b6528aedbb
Revises: 
Create Date: 2025-04-27 00:10:58.447622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83b6528aedbb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toto_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_number')
    )
    op.create_table('toto_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('winning_numbers', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('additional_number', sa.Integer(), nullable=False),
    sa.Column('draw_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('jackpot', sa.DECIMAL(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toto_results_draw_date'), 'toto_results', ['draw_date'], unique=False)
    op.create_index(op.f('ix_toto_results_draw_number'), 'toto_results', ['draw_number'], unique=True)
    op.create_table('snowball_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['draw_number'], ['toto_results.draw_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_number', 'group_number')
    )
    op.create_index(op.f('ix_snowball_info_draw_number'), 'snowball_info', ['draw_number'], unique=False)
    op.create_table('winning_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.DECIMAL(), nullable=False),
    sa.Column('winner_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draw_number'], ['toto_results.draw_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_number', 'group_number')
    )
    op.create_table('winning_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draw_number', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.Integer(), nullable=False),
    sa.Column('outlet_name', sa.Text(), nullable=False),
    sa.Column('outlet_address', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('is_itoto', sa.Boolean(), nullable=True),
    sa.Column('ticket_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['draw_number'], ['toto_results.draw_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draw_number', 'group_number', 'ticket_order')
    )
    op.create_index(op.f('ix_winning_tickets_draw_number'), 'winning_tickets', ['draw_number'], unique=False)
    op.create_table('itoto_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('outlet_name', sa.Text(), nullable=False),
    sa.Column('outlet_address', sa.Text(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('location_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['winning_tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id', 'location_order')
    )
    op.create_index(op.f('ix_itoto_locations_ticket_id'), 'itoto_locations', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itoto_locations_ticket_id'), table_name='itoto_locations')
    op.drop_table('itoto_locations')
    op.drop_index(op.f('ix_winning_tickets_draw_number'), table_name='winning_tickets')
    op.drop_table('winning_tickets')
    op.drop_table('winning_shares')
    op.drop_index(op.f('ix_snowball_info_draw_number'), table_name='snowball_info')
    op.drop_table('snowball_info')
    op.drop_index(op.f('ix_toto_results_draw_number'), table_name='toto_results')
    op.drop_index(op.f('ix_toto_results_draw_date'), table_name='toto_results')
    op.drop_table('toto_results')
    op.drop_table('toto_page')
    # ### end Alembic commands ###
